# -*- coding: utf-8 -*-
"""Catalog Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sxqmVWLf_pJSypIPSM2UCK-Yw6qkHKi
"""
from dotenv import load_dotenv
load_dotenv()
import os

def create_catalog():
    os.makedirs("data/catalog", exist_ok=True)

    # 1. Academic Policies
    policies = {
        "policy_registration": ("Academic Policies - Registration", "https://uni.edu/catalog/policies/registration", "Students may enroll in a maximum of 18 credits per term. To exceed this, instructor consent and department approval are required. All prerequisite courses must be completed with a minimum grade of 'C' unless otherwise noted."),
        "policy_transfers": ("Academic Policies - Transfers", "https://uni.edu/catalog/policies/transfers", "Transfer credits are accepted upon evaluation. However, residency requirements mandate that the final 30 credits of any degree must be taken at this university.")
    }

    # 2. Program Requirements
    programs = {
        "prog_bscs": ("BS Computer Science Requirements", "https://uni.edu/catalog/programs/bscs", "The BS in Computer Science requires completion of Core: CS101, CS102, MATH120, CS201, CS301, CS302. Students must also complete 2 Electives from the 400-level CS courses."),
        "prog_minordata": ("Minor in Data Science", "https://uni.edu/catalog/programs/minor-ds", "The minor in Data Science requires MATH120, CS101, CS302, and DS400.")
    }

    # 3. Courses (21 courses to meet the 25+ total docs requirement)
    courses = {
        "MATH120": ("Calculus I", "4 credits. Prerequisite: None. Introduction to limits, derivatives, and integrals."),
        "MATH220": ("Calculus II", "4 credits. Prerequisite: MATH120. Advanced integration and series."),
        "CS101": ("Intro to Programming", "3 credits. Prerequisite: None. Basics of Python programming."),
        "CS102": ("Object-Oriented Programming", "3 credits. Prerequisite: CS101 with a min grade of C. Java programming and classes."),
        "CS201": ("Data Structures", "3 credits. Prerequisite: CS102 AND MATH120. Lists, trees, graphs, and algorithm analysis."),
        "CS202": ("Computer Architecture", "3 credits. Prerequisite: CS102. Hardware basics and assembly."),
        "CS301": ("Algorithms", "3 credits. Prerequisite: CS201. Advanced algorithm design."),
        "CS302": ("Database Systems", "3 credits. Prerequisite: CS201. Co-requisite: CS303. Relational databases and SQL. Co-requisite must be taken concurrently."),
        "CS303": ("Database Lab", "1 credit. Co-requisite: CS302. Practical SQL lab."),
        "CS305": ("Operating Systems", "3 credits. Prerequisite: CS201 AND CS202. Processes, threads, and memory."),
        "CS401": ("Artificial Intelligence", "3 credits. Prerequisite: CS301. Search, logic, and ML basics."),
        "CS402": ("Machine Learning", "3 credits. Prerequisite: CS401 AND MATH220. Neural networks and statistical learning. Exception: Can be taken without MATH220 with instructor consent."),
        "CS403": ("Software Engineering", "3 credits. Prerequisite: CS302. Agile, scrums, and system design."),
        "CS404": ("Cybersecurity", "3 credits. Prerequisite: CS305. Cryptography and network security."),
        "CS405": ("Cloud Computing", "3 credits. Prerequisite: CS302. AWS, Docker, and distributed systems."),
        "DS400": ("Data Mining", "3 credits. Prerequisite: CS302 AND MATH120. Extracting patterns from large data."),
        "ENG101": ("College Writing", "3 credits. Prerequisite: None. Academic writing and research."),
        "PHYS101": ("Physics I", "4 credits. Prerequisite: MATH120. Mechanics and thermodynamics."),
        "PHYS102": ("Physics II", "4 credits. Prerequisite: PHYS101. Electromagnetism."),
        "ART101": ("Intro to Art", "3 credits. Prerequisite: None. History of visual arts."),
        "HIST101": ("World History", "3 credits. Prerequisite: None. Global historical survey.")
    }

    files_created = 0

    # Write Policies
    for k, (title, url, text) in policies.items():
        with open(f"data/catalog/{k}.md", "w") as f:
            f.write(f"URL: {url}\nTITLE: {title}\n\n{text}")
            files_created += 1

    # Write Programs
    for k, (title, url, text) in programs.items():
        with open(f"data/catalog/{k}.md", "w") as f:
            f.write(f"URL: {url}\nTITLE: {title}\n\n{text}")
            files_created += 1

    # Write Courses
    for k, (title, text) in courses.items():
        url = f"https://uni.edu/catalog/courses/{k.lower()}"
        with open(f"data/catalog/course_{k.lower()}.md", "w") as f:
            f.write(f"URL: {url}\nTITLE: {k} - {title}\n\nCourse Code: {k}\nTitle: {title}\n{text}")
            files_created += 1

    print(f"✅ Successfully generated {files_created} distinct catalog documents in 'data/catalog/'.")

if __name__ == "__main__":
    create_catalog()
