# -*- coding: utf-8 -*-
"""Ingestion Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132c7aEjqZH4UpWVRh37OUSSSrWGyH66s
"""
from dotenv import load_dotenv
load_dotenv()
import os
import glob
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
from langchain_community.vectorstores import Chroma

DB_DIR = "data/chroma_db"
CATALOG_DIR = "data/catalog"

def ingest_data():
    print("Loading documents...")
    files = glob.glob(f"{CATALOG_DIR}/*.md")

    docs = []
    for file_path in files:
        # Extract URL and Title for metadata
        with open(file_path, 'r') as f:
            lines = f.readlines()
            url = lines[0].replace("URL:", "").strip() if "URL:" in lines[0] else "Unknown URL"
            title = lines[1].replace("TITLE:", "").strip() if "TITLE:" in lines[1] else "Unknown Title"
            content = "".join(lines[2:]).strip()

            from langchain_core.documents import Document
            docs.append(Document(page_content=content, metadata={"url": url, "title": title}))

    print(f"Loaded {len(docs)} documents.")

    # Chunking Strategy:
    # Size 500, Overlap 50. Courses and policy paragraphs are short.
    # This prevents merging unrelated course prerequisites into the same chunk,
    # which causes LLM hallucination on prerequisite chains.
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=300,
        chunk_overlap=30,
        separators=["\n\n", "\n", ".", " "]
    )
    splits = text_splitter.split_documents(docs)
    print(f"Created {len(splits)} chunks.")

    print("Building Vector Store (Chroma)...")
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

    # Clear old DB if exists
    if os.path.exists(DB_DIR):
        import shutil
        shutil.rmtree(DB_DIR)

    vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings, persist_directory=DB_DIR)
    vectorstore.persist()
    print("✅ Ingestion complete. Vector store saved to", DB_DIR)

if __name__ == "__main__":
    ingest_data()
